development:
  adapter: mysql2
  database: website_development
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: website_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: website_production
  username:
  password:
  pool: 5
  timeout: 5000

